version: '3.8'
services:
  service1:
    image: abdulbutt123/frontend:latest
    build: ./service_1
    container_name: service1
    deploy:
      replicas: 1
    networks:
      - meal-net
  service2:
    image: abdulbutt123/random_breakfast:latest
    build: ./service_2
    container_name: service2
    deploy:
      replicas: 1
    networks:
      - meal-net
  service3:
    image: abdulbutt123/random_lunch:latest
    build: ./service_3
    container_name: service3
    deploy:
      replicas: 1
    networks:
      - meal-net
  service4:
    image: abdulbutt123/overallcalories:latest
    build: ./service_4
    container_name: service4
    deploy:
      replicas: 1
    networks:
      - meal-net
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - meal-net
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - service1
networks:
  meal-net: